blog/urls.py
from django.urls import path
from .views import BlogPostListView, BlogPostDeleteView, BlogPostDetailView, BlogPostUpdateView, BlogPostCreateView
from django.views.decorators.cache import cache_page

app_name = 'blog'

urlpatterns = [
    path('', BlogPostListView.as_view(), name='list'),
    path('detail/<slug>/', cache_page(60)(BlogPostDetailView.as_view()), name='detail'),
    path('create/', BlogPostCreateView.as_view(), name='create'),
    path('update/<slug>/', BlogPostUpdateView.as_view(), name='update'),
    path('delete/<slug>/', BlogPostDeleteView.as_view(), name='delete'),
]

mailing/urls.py
from django.urls import path
from .views import MailingCreateView, MailingDetailView, MessageCreateView, ClientListView, MailingListView, HomeView, \
    DeliveryReportView, MailingDeleteView, ClientCreateView, MailingUpdateView
from django.views.decorators.cache import cache_page

app_name = 'mailing'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('mailing/', MailingListView.as_view(), name='mailing'),
    path('create_mailing/', MailingCreateView.as_view(), name='create_mailing'),
    path('mailing/delete/<int:pk>/', MailingDeleteView.as_view(), name='delete_mailing'),
    path('mailing/update/<int:pk>/', MailingUpdateView.as_view(), name='update_mailing'),
    path('mailing/<int:pk>/', cache_page(60)(MailingDetailView.as_view()), name='mailing_detail'),
    path('clients/', ClientListView.as_view(), name='client_list'),
    path('clients/create/', ClientCreateView.as_view(), name='create_client'),
    path('mailing/<int:mailing_pk>/create_message/', MessageCreateView.as_view(), name='create_message'),
    path('delivery_report/', cache_page(60)(DeliveryReportView.as_view()), name='delivery_report'),
]

skychimp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls')),
    path('users/', include('users.urls')),
    path('blog/', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/models.py
from django.conf import settings
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    email = models.EmailField(unique=True)
    full_name = models.CharField(max_length=255)
    comment = models.TextField(blank=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE)
    is_active = models.BooleanField(default=True, verbose_name='Активный')

    def __str__(self):
        return self.full_name


class Mailing(models.Model):
    start_time = models.DateTimeField()
    frequency_choices = [
        ('daily', 'Daily'),
        ('weekly', 'Weekly'),
        ('monthly', 'Monthly'),
    ]
    frequency = models.CharField(max_length=10, choices=frequency_choices)
    status_choices = [
        ('created', 'Created'),
        ('started', 'Started'),
        ('completed', 'Completed'),
    ]
    status = models.CharField(max_length=10, choices=status_choices)
    recipients = models.ManyToManyField(Client)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE)


class Message(models.Model):
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE)
    subject = models.CharField(max_length=255)
    body = models.TextField()
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE)


class Log(models.Model):
    message = models.ForeignKey(Message, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=20)
    response = models.TextField(blank=True)

mailing/forms.py
from django import forms
from .models import Mailing, Message, Client


class MailingForm(forms.ModelForm):
    class Meta:
        model = Mailing
        fields = ['start_time', 'frequency', 'recipients', 'status']
        widgets = {
            'recipients': forms.CheckboxSelectMultiple,
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(MailingForm, self).__init__(*args, **kwargs)
        if user:
            self.fields['recipients'].queryset = user.client_set.all()


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['subject', 'body']


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['email', 'full_name', 'comment', 'is_active']

        widgets = {
            'comment': forms.Textarea(attrs={'rows': 4}),  # Можно настроить виджет для текстового поля 'comment'
        }

mailing/views.py
from random import sample
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, CreateView, DetailView, DeleteView, UpdateView
from blog.models import BlogPost
from .models import Mailing, Client, Message, Log
from .forms import MailingForm, MessageForm, ClientForm


class HomeView(TemplateView):
    template_name = 'mailing/home.html'
    extra_context = {
        'title': 'Главная страница',
    }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['count_mailing'] = len(Mailing.objects.all())
        active_mailings_count = Mailing.objects.filter(status__in=['created', 'started']).count()
        context['active_mailings_count'] = active_mailings_count
        unique_clients_count = Client.objects.filter(is_active=True).distinct().count()
        context['unique_clients_count'] = unique_clients_count
        all_posts = list(BlogPost.objects.all())
        context['random_blog_posts'] = sample(all_posts, min(3, len(all_posts)))
        context['object_list'] = Mailing.objects.all()
        user = self.request.user
        user_group_names = [group.name for group in user.groups.all()]
        context['user_group_names'] = user_group_names
        return context


class MailingListView(ListView):
    model = Mailing
    template_name = 'mailing/mailing_list.html'
    context_object_name = 'mailings'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        user_group_names = [group.name for group in user.groups.all()]
        context['user_group_names'] = user_group_names
        return context


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForm
    template_name = 'mailing/create_mailing.html'

    def form_valid(self, form):
        new_mailing = form.save()
        new_mailing.owner = self.request.user
        new_mailing.save()
        self.mailing_pk = new_mailing.pk
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_success_url(self):
        return reverse_lazy('mailing:create_message', kwargs={'mailing_pk': self.mailing_pk})


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    model = Mailing
    fields = ('start_time', 'frequency', 'recipients', 'status')
    success_url = reverse_lazy('mailing:mailing')

    def form_valid(self, form):
        if form.is_valid():
            new_mailing = form.save()
            new_mailing.owner = self.request.user
            new_mailing.save()
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['initial'] = {'user': self.request.user}
        return kwargs

    def get_object(self, queryset=None):
        mailing = super().get_object(queryset)
        mailing = get_object_or_404(Mailing, id=mailing.pk)
        user_groups = [group.name for group in self.request.user.groups.all()]
        if mailing.owner != self.request.user and 'Managers' not in user_groups:
            raise Http404
        return mailing


class MailingDetailView(DetailView):
    model = Mailing
    template_name = 'mailing/mailing_detail.html'
    context_object_name = 'mailing'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['messages'] = Message.objects.filter(mailing=self.object)
        return context


class MailingDeleteView(LoginRequiredMixin, DeleteView):
    model = Mailing
    success_url = reverse_lazy('mailing:mailing')
    extra_context = {
        'title': 'Удаление записи:'
    }

    def get_object(self, queryset=None):
        mailing = super().get_object(queryset)
        mailing = get_object_or_404(Mailing, id=mailing.pk)
        user_groups = [group.name for group in self.request.user.groups.all()]
        if mailing.owner != self.request.user and 'Managers' not in user_groups:
            raise Http404
        return mailing


class ClientListView(ListView):
    model = Client
    template_name = 'mailing/client_list.html'
    context_object_name = 'clients'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        user_group_names = [group.name for group in user.groups.all()]
        context['user_group_names'] = user_group_names
        return context


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:mailing')
    raise_exception = True

    def get_context_data(self, *, object_list=None, **kwargs):
        data = super().get_context_data(object_list=None, **kwargs)
        data['title'] = "Создание нового клиента."
        return data

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    template_name = 'mailing/create_message.html'
    success_url = reverse_lazy('mailing:mailing')

    def form_valid(self, form):
        mailing = get_object_or_404(Mailing, pk=self.kwargs['mailing_pk'])
        message = form.save(commit=False)
        message.mailing = mailing
        message.save()
        return super().form_valid(form)


class DeliveryReportView(ListView):
    model = Log
    template_name = 'mailing/delivery_report.html'
    context_object_name = 'delivery_logs'

    def get_queryset(self):
        return Log.objects.filter(status='success')

mailing/templates/malling/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {{ title }}
    </title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h4 class="my-0 mr-md-auto font-weight-normal">SkyChimp</h4>
    <div class="col-9">
        <nav class="ms-5">
            <a class="p-2 btn btn-outline-primary" href="/">Главная</a>
            <a class="p-2 btn btn-outline-primary" href="/clients/">Клиенты</a>
            <a class="p-2 btn btn-outline-primary" href="/mailing/">Рассылки</a>
            <a class="p-2 btn btn-outline-primary" href="/delivery_report/">Отчеты о доставке</a>
            <a class="p-2 btn btn-outline-primary" href="/blog/">Блог</a>
        </nav>
    </div>
    <div class="col-2">
        <div class="btn-group">
            <button type="button" class="btn btn-outline-primary dropdown-toggle btn-lg" data-bs-toggle="dropdown"
                    aria-expanded="false">
                {% if user.is_authenticated %}
                    {{ user.email }}
                {% else %}
                    Войти
                {% endif %}
            </button>
            {% if user.is_authenticated %}
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="/users/profile">Профиль</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="/users/logout">Выйти</a></li>
                </ul>
            {% else %}
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="/users">Войти</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="/users/register">Регистрация</a></li>
                </ul>
            {% endif %}
        </div>
    </div>
</div>
{% block content %}

{% endblock %}

<div class="container">
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                Skychimp
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

mailing/templates/malling/client_form.html
{% extends 'mailing/base.html' %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">

                            {% csrf_token %}

                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">
                                {% if object %}
                                Сохранить
                                {% else %}
                                Создать
                                {% endif %}
                            </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </form>
{% endblock %}

mailing/templates/malling/client_list.html
{% extends 'mailing/base.html' %}
{% block content %}

    <h2>Client List</h2>
    {% if user.is_authenticated %}
        <div class="col-12 mb-5">
            <a class="btn btn-outline-primary" href="{% url 'mailing:create_client' %}">Добавить запись</a>
        </div>
    {% endif %}
    <ul>
        {% for client in clients %}
            <li>{{ client.full_name }} ({{ client.email }})</li>
        {% endfor %}
    </ul>
{% endblock %}

mailing/templates/malling/create_mailing.html
{% extends 'mailing/base.html' %}

{% block content %}
<h2>Create Mailing</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Create Mailing</button>
</form>
{% endblock %}

mailing/templates/malling/create_message.html
{% extends 'mailing/base.html' %}

{% block content %}
<h2>Create Message</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Create Message</button>
</form>
{% endblock %}

mailing/templates/malling/customer_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                           <p>
                               Хотите удалить клиента "{{ object.name }}"
                           </p>
                            <button type="submit" class="btn btn-success">
                                Подтвердить
                            </button>
                            <a href="{% url 'sender:customer_list' %}" class="btn btn-success">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}>

mailing/templates/malling/delivery_report.html
{% extends 'mailing/base.html' %}

{% block content %}
  <h1>Отчет о доставке рассылок</h1>
  <table>
    <thead>
      <tr>
        <th>Дата и время</th>
        <th>Статус</th>
        <th>Ответ сервера</th>
      </tr>
    </thead>
    <tbody>
      {% for log in delivery_logs %}
        <tr>
          <td>{{ log.timestamp }}</td>
          <td>{{ log.status }}</td>
          <td>{{ log.response }}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="3">Нет данных о доставке</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

mailing/templates/malling/home.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% block content %}
    <div class="row gy-5">
        <h4> Сервис рассылки сообщений</h4>
        <div class="col">
            <div class="card shadow-sm text-center" style="background: #e0e0e0">
                <figure class="p-3 mb-0">
                    Создано рассылок: {{ count_mailing }} .<br>
                    <br>
                    Количество активных рассылок: {{ active_mailings_count }}.<br>
                    <br>
                    Количество уникальных клиентов {{ unique_clients_count }}:
                </figure>
            </div>
        </div>
    </div>
    <br>
    <div class="row text-center">
        {% for item in random_blog_posts %}
            <div class="col-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ item.title }}</h4>
                    </div>
                    <div class="card-body">
                        <a href="{% url 'blog:detail' item.slug %}">
                            <img alt="Фото" class="card-img-top" style="width: 75%"
                                 src="{{ item.preview_image|media_url }} ">
                        </a>
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <li>Содержание: {{ item.content|truncatechars:100 }}</li>
                        </ul>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{% url 'blog:detail' item.slug %}" class="btn btn-sm btn-outline-secondary">Подробно</a>
                                {% if item.owner.email == user.email or 'Managers' in user_group_names %}
                                    <a href="{% url 'blog:update' item.slug %}"
                                       class="btn btn-sm btn-outline-secondary">Редактировать</a>
                                    <a href="{% url 'blog:delete' item.slug %}"
                                       class="btn btn-sm btn-outline-secondary">Удалить</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}

    </div>
    <br>
{% endblock %}

mailing/templates/malling/mailing_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                           <p>
                               Хотите удалить эту рассылку?
                           </p>
                            <button type="submit" class="btn btn-success">
                                Подтвердить
                            </button>
                            <a href="/" class="btn btn-success">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}>

mailing/templates/malling/mailing_detail.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="px-4 ">
        <div class="col-6">
            <h2>Mailing Details</h2>
            <p>Mailing ID: {{ mailing.id }}</p>
            <p>Start Time: {{ mailing.start_time }}</p>
            <p>End Time: {{ mailing.end_time }}</p>
            {% for message in messages %}
                <p>Message ID: {{ message.id }}</p>
            {% endfor %}
        </div>
    </div>

{% endblock %}

mailing/templates/malling/mailing_form.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">
                                {% if object %}
                                Сохранить
                                {% else %}
                                Создать
                                {% endif %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mailing/templates/malling/mailing_list.html
{% extends 'mailing/base.html' %}

{% block content %}
    <h2>Mailing List</h2>
    <ul>
        {% if user.is_authenticated %}
            <div class="col-12 mb-5">
                <a class="btn btn-outline-primary" href="{% url 'mailing:create_mailing' %}">Добавить запись</a>
            </div>
        {% endif %}
        {% for mailing in mailings %}

            <li><a href="{% url 'mailing:mailing_detail' mailing.pk %}">{{ mailing.start_time }}
                - {{ mailing.end_time }}  </a>
                {% if mailing.owner.email == user.email or 'Managers' in user_group_names %}
                    <a class="btn btn-outline-primary" href="{% url 'mailing:delete_mailing' mailing.pk %}">Удалить</a>
                    <a class="btn btn-outline-primary" href="{% url 'mailing:update_mailing' mailing.pk %}">Редактировать</a>
                {% endif %}
            </li>
        {% endfor %}
    </ul>
{% endblock %}